### ISSUE TITLE
Find edges of Graph by mouse click

### ISSUE THREAD

**Issue by khanhdv** [graphstream/gs-core#112]
I have a project which uses graphstream. My problem is when i click the right mouse into one edge, i need to know the ID of that edge where the cursor of mouse overs on it, how can i do that?

**Comment by KurtCh** [comment]
Hey,
I know this is an old post. But, I wanted to do the same, and I came across this post, and I figured out a way to do it. So, here is how you detect a click on an edge:

![idea](https://user-images.githubusercontent.com/26008843/71950449-4843f700-31a5-11ea-9711-0e3480b3754a.png)

The basic idea is that given the coordinates of the 2 nodes (n0 and n1) to which the edge is connected, we can determine if the mouse clicked close enough to the edge to be registered as a click. We do this by first making the equation of the line that passes through both nodes, and then determining the distance of the mouse click from that line. As well as checking that the mouse click is withing the bounds of the edge (Mouse.x is not to the left of the leftmost node or to the right of the rightmost node, because then the click will not be on the edge even though it may be close to the line equation we derived. Same with Mouse.y)

The add code option wasn't working for me so I just added a picture of the code, and the code itself in a text file (I am using autolayout for my graph which is why I get the node coordinates like this).

![edgeclick](https://user-images.githubusercontent.com/26008843/72110597-93c1e680-3306-11ea-9a4a-f477da1fadcf.PNG)
[clickedge.txt](https://github.com/graphstream/gs-core/files/4042882/clickedge.txt)
