### ISSUE TITLE
Graphstream is case sensitive

### ISSUE THREAD

**Issue by rafatp** [graphstream/gs-core#154]
Hello everyone!
I'm trying to implement a gene regulatory network on GraphStream, but in some cases when I have the same gene and protein name (like CRP->crp) it returns an exception. One reason for this, in my opinion, might be the same name to different nodes. Some suggestion?? Thanks!
Exception report:
 org.graphstream.graph.EdgeRejectedException: Edge 1[CRP--crp] was rejected by node CRP

**Comment by gsavin** [comment]
Can not reproduce this bug with :
```java
Graph g = new SingleGraph("g");
g.addNode("CRP");
g.addNode("crp");
g.addEdge("1", "CRP", "crp");
```
With any of the graph implementations.

**Comment by pigne** [comment]
"CRP" and "crp" are two different strings (with a different hash) so it's OK to have two nodes with these names. The error says you already have an edge between node '"CRP" and node "crp". Maybe you tried to add it twice? 

If you want multiple edges between two nodes then consider using the [MultiGraph](http://graphstream-project.org/api/gs-core/org/graphstream/graph/implementations/MultiGraph.html) implementation instead of SingleGraph.

**Comment by rafatp** [comment]
Thanks for your quickly answer!
You are right,Yoann! I must use a MultiGraph approach!
Thanks
