### ISSUE TITLE
invalid node attribute 'labels' (readAll(fileFromNeo4jGraphMLExport.graphml)

### ISSUE THREAD

**Issue by AfterEight** [graphstream/gs-core#176]
Hello, 
I've got a graphml exported from a neo4j instance.
The first lines of the graphml look like this: 
```
<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
<graph id="G" edgedefault="directed">
<node id="n29" labels=":Page"><data key="labels">:Page</data><data key="title">ArtificialLanguages</data></node>
```
Trying to read this file with GraphStream results in 

ParseError at [row,col]:[4,1]
Message: invalid node attribute 'labels'

Is there a way for me to extend the parser with the attribute? (Btw. Gephi is able to read and display the file) 
Thanks in advance

**Comment by gsavin** [comment]
The `GraphML` source is based on the [GraphML DTD](http://graphml.graphdrawing.org/dtds/graphml.dtd), which does not contain a `labels` attribute.

**Comment by AfterEight** [comment]
Hello, thanks to your answer. That is a reason, why I gave the example that Gephi is able to skip information not given in the DTD. So it's rather an issue of handling those cases. With respect to the fact graphml is nothing else than xml, I do not like the answer. To interested users: JUNG API can handle the issue.

**Comment by gsavin** [comment]
Well, feel free to use another software if it has a better fit to your needs. If you are using GraphStream just for the GraphML support, I guess you definitely should. Our main goal is to provide support for dynamics.

Even if GraphML is just XML, there is a formal definition of its structure, and we try to follow these specifications for each format.

However, there is now a _strict mode_ that can be disabled and allowing unexpected attributes. Your example will still not work since it uses `data` element referencing a non-existing `key`.
