### ISSUE TITLE
GraphStream for JavaFX

### ISSUE THREAD

**Issue by jordilaforge** [graphstream/gs-core#231]
Dear Dev Team

I have been working a lot with graphstream lately and it is a good library. But the thing that bothers me most is that graphstream is still based on awt and swing. Nowadays a lot of application are running with javafx as gui. Yes, there is swingnode but that's not a clean solution. So my question is how much work would it be to make graphstream compatible with javafx? I looked into the roadmap but it doesn't seem to be planned in the future. I would like to look into that my own but I don't know where to start. Is it enough to write a new renderer or do I have to rewrite the whole core without awt and swing?
Thanks for the help
jordi

**Comment by gsavin** [comment]
Hi,

That's a good question. With the last release we start to cut off the links between the core of GraphStream and AWT/SWING. The goal was/is to provide a generic interface for the UI so one can be able to use its favorites framework. We are close to finalize this separation.

On the other hand, one of the main objectives of the next major release is to use Java 8. Work is already started on the 2.x branch. I believe that using Java 8 will lead to get a JavaFX version of the viewer. We need to define a clear roadmap for all of this.

**Comment by jordilaforge** [comment]
Hi gsavin
That sounds very promising. But using Java8 doesn't make Swing and AWT disappearing right away, or am I wrong. What changes are made by using Java8? Do you have a roadmap or stories which need to be done?
I would like to help out where I can.
Greetz

**Comment by gsavin** [comment]
You are absolutely right, SWING will not disappear now. But JavaFX is the successor of SWiNG and the latter will not improved anymore (except for bug fixing of course), so now that's JavaFX is included in Java8, it makes sense to switch to this graphic framework if we want to keep GraphStream up to date with Java practices. In an ideal future where we succeed to have a JavaFX viewer, I guess we would put the SWING in a independent package to keep gs-core light. These are just loud thoughts.

Changes to GraphStream brought by Java8 rely mostly on streams and lambda functions. The way we access elements in GS2 is done through streams. The goal is to abstract the way elements are stored, opening the way for a graph who quietly access to its elements from a graph database for example. Because of this, and some others features of Java8, code becomes lighter. You can have a look on the 2.x dev branch on GitHub if you want to know more about it.

As I told you, roadmap is not yet finalized, but we will put it online once done. I guess all help will be welcome then :-) Thanks for that.

**Comment by stothet** [comment]
Hi, I am still not sure if there is a way for me to use GraphStream in conjunction with JavaFX. Would it require for me to make an adapter class? or some other rendering? Or is it not possible with the latest release? a newbie here. thanks!

**Comment by jordilaforge** [comment]
hi stothet
Well GraphStream is based on Swing, if you want to include graphstream in a java fx application you have to use a SwingNode. Place the graph in the swingnode and then you can place the SwingNode in any fx node you like. It works but it is a mess because any action on the graph has to be done in an awt thread and any action on fx elements in a fx thread. 
Hope that helps

**Comment by gsavin** [comment]
JavaFX viewer now available with https://github.com/graphstream/gs-ui-javafx
