### ISSUE TITLE
How to generate a graph with 10th of millions of nodes?

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [graphstream/gs-core#236]
I'm trying to generate a graph with the `BarabasiAlbertGenerator` (m=2). My goal is to generate a graph with 30 million nodes or even better 50 or 100 million nodes.

My current implementation works fine up to 4.5 million nodes and gets stuck by ~ 4.8 million nodes (95% CPU usage and no more progress for hours).

Is it possible to generate such huge graphs with this library? Has anyone done this before?

I guess one of the bottlenecks is the list of degrees (https://github.com/graphstream/gs-algo/blob/master/src/org/graphstream/algorithm/generator/BarabasiAlbertGenerator.java#L93).

I'm already using the `AdjacencyListGraph` (https://github.com/graphstream/gs-core/blob/master/src/org/graphstream/graph/implementations/AdjacencyListGraph.java) to reduce the memory footprint.

**Comment by pigne** [comment]
The problem is not the generation of the graph. The BarabasiAlbertGenerator has a linear memory complexity but it has a time complexity of roughly n^2. 

Maybe some optimization are possible on the way the list of degrees is handled or how random draws are done, but still we won't break the squared complexity.
