### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by sidletsky** [graphstream/gs-core#262]
Using VisualVM I discovered that graphstream library has memory leak
<img width="418" alt="2017-12-25 12 11 33" src="https://user-images.githubusercontent.com/9529998/34339122-220f3f38-e970-11e7-8f48-4812500df234.PNG">

**Comment by jordilaforge** [comment]
hi sidletsky
I experienced the same especially if you use a custom CSS file. Maybe you can dig a bit deeper and find out what exactly is leaking....

**Comment by josephmate** [comment]
That's not enough information to conclude that there's a memory leak. The heap used drops at the end, indicating that the garbage collector eventually reclaimed the un-used memory.

You will often see upward trends on heap used like in the chart you posted because the garbage collector does not reclaim memory immediately after it becomes reclaimable.
