### ISSUE TITLE
SwingViewer package import error

### ISSUE THREAD

**Issue by SOUMAJYOTI** [graphstream/gs-core#288]
When I try to integrate the viewer in a GUI and try to import the following two packages, 
```
import  org.graphstream.ui.swingViewer.View;
import org.graphstream.ui.swingViewer.Viewer;
```
the project is not able to find them and import,. I am using **gs-ui-1.3.jar**. Additionally I also tried **gs-swing-ui.jar** but none of them work. What am I missing here ?

On a side note, I really feel that the latest package versions and the tutorial are not synced up and as such the package hierarchy is messed up, especially for gs-core/ui. The tutorial is based on parts of gs-core-1.2 and partly on gs-core-1.3. But many methods in gs-core-1.2 has been deprecated which has not been taken care of in the tutorial.

**Comment by hichbra** [comment]
Hi!

gs-ui and gs-ui-swing are two different versions of the same thing. When we switched to the 2.0, gs-ui has been split into several project, based on the GUI tech.

Thus, if you work with Graphstream 1.3 use gs-ui, otherwise if you want to use Graphstream 2.0, then look gs-ui-swing/javafx...

For GS 1.3, you can look the [documentation](http://graphstream-project.org/doc/Tutorials/Graph-Visualisation/ ), it's reasonably complete and correct. 

For the 2.0-alpha, no documentation is officialy provided yet, but a large majority of the actual documentation is still valid. Also, I advise you to look the examples [here](https://github.com/graphstream/gs-ui-swing/tree/2.0-alpha/src-test/org/graphstream/ui/viewer_swing/test).

Good luck.

**Comment by SOUMAJYOTI** [comment]
@hichbra If you go to the code repository in gs-core/ui/SwingViewer linked [here](https://github.com/graphstream/gs-core/tree/1.3/src/org/graphstream/ui/swingViewer
), you will find that there is no class with name **View** and **Viewer**. When I try to import the above mentioned two classes as mentioned before 

> import  org.graphstream.ui.swingViewer.View;
> import org.graphstream.ui.swingViewer.Viewer;

the import error is raised. Am I missing anything here?

**Comment by hichbra** [comment]
In gs-core 1.3, View and Viewer are in [view](https://github.com/graphstream/gs-core/tree/1.3/src/org/graphstream/ui/view) package. 

swingViewer contains the required classes of the default graph renderer.

**Comment by SOUMAJYOTI** [comment]
Thanks for the comments. But still, would appreciate if someone could just update that part of the tutorial with this information.
